config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items
  resources :categories
  resources :places
  post 'items' => 'items#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :place, optional: true
  REGISTRABLE_ATTRIBUTES = %i(
    name
    arrival_date(1i) arrival_date(2i) arrival_date(3i)
    )
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @items = @category.items.order("expiration_date")
    @places = Place.all
  end

  def new
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to new_category_path
    else
      render :new
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to new_category_path

  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new

  end

  def index
    @categories = Category.all
    @places = Place.all
    @items = Item.order("expiration_date")
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to new_item_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_back(fallback_location: 'something')
    else
      render :index
    end

  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to items_path

  end

  private

  def item_params
    params.require(:item).permit(:name, :count, :category_id, :place_id, :expiration_date)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def new
    @place = Place.new
    @places = Place.all
  end

  def show
    @categories = Category.all
    @place = Place.find(params[:id])
    @items = @place.items.order("expiration_date")
    @places = Place.all
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to items_path
    else
      render :new
    end
  end

  def update

  end

  def destroy
    place = Place.find(params[:id])
    place.destroy
    redirect_to new_place_path

  end

  private

  def place_params
    params.require(:place).permit(:name)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    items_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    items_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/categories/new.html.erb
<%= render "layouts/header" %>
<%= form_for(@category, url: categories_path(@category)) do |f| %>
  <h4>ジャンル</h4>
  <br>
  <%= f.text_field :name %>
  <%= f.submit "追加", class: "btn btn-primary" %>
<% end %>
<br>
<table class="table  table-inverse">
  <thead>
  <tr>
    <% @categories.each do |category| %>

      <th><%= category.name %></th>
      <th><%= link_to '消去', category_path(category), method: :delete %></th>

    <% end %>
  </tr>
  </thead>
</table>

app/views/categories/show.html.erb
<%= render "layouts/header" %>
<table class="table table-bordered">
  <tbody>
  <th>カテゴリー</th>
  <% @categories.each do |category| %>

    <th><%= link_to category.name, category_path(category) %></th>
  <% end %>
  </tbody>
  <tbody>
  <th>場所</th>
  <% @places.each do |place| %>

    <th><%= link_to place.name, place_path(place) %></th>
  <% end %>

  </tbody>
</table>
<div>

  <h2>商品一覧（全<%= @items.count %>件）</h2>

  <table class="table  table-inverse">
    <thead>
    <tr>
      <th>名前</th>
      <th>ジャンル</th>
      <th>場所</th>
      <th>賞味期限</th>
      <th>個数</th>
    </tr>
    </thead>

    <tbody>

    <tr>
      <% @items.each do |item| %>
        <td><%= item.name %></td>

        <% category = Category.find(item.category_id) %>
        <td><%= category.name %></td>

        <% place = Place.find(item.place_id) %>
        <td><%= place.name %></td>
        <td><%= item.expiration_date %></td>


        <td>
          <%= form_for(item, url: item_path(item), method: :patch) do |f| %>
            <%= f.select :count, (1..200) %>
            <%= f.submit "変更する" %>
            </td>

            <td><%= link_to '消去', item_path(item), method: :delete %></td>
            </tr>
            </tbody>
          <% end %>
      <% end %>
      </table>


</div>

app/views/items/index.html.erb
<%= render "layouts/header" %>
<table class="table table-bordered">
  <tbody>
  <th>カテゴリー</th>
  <% @categories.each do |category| %>

    <th><%= link_to category.name, category_path(category) %></th>
  <% end %>
  </tbody>
  <tbody>
  <th>場所</th>
  <% @places.each do |place| %>

    <th><%= link_to place.name, place_path(place) %></th>
  <% end %>

  </tbody>
</table>
<div>

  <h2>商品一覧（全<%= @items.count %>件）</h2>

  <table class="table  table-inverse">
    <thead>
    <tr>
      <th>名前</th>
      <th>ジャンル</th>
      <th>場所</th>
      <th>賞味期限</th>
      <th>個数</th>
    </tr>
    </thead>

    <tbody>

    <tr>
      <% @items.each do |item| %>
        <td><%= item.name %></td>

        <% category = Category.find(item.category_id) %>
        <td><%= category.name %></td>

        <% place = Place.find(item.place_id) %>
        <td><%= place.name %></td>
        <td><%= item.expiration_date %></td>


        <td>
          <%= form_for(item, url: item_path(item), method: :patch) do |f| %>
            <%= f.select :count, (1..200) %>
            <%= f.submit "変更する" %>
            </td>

            <td><%= link_to '消去', item_path(item), method: :delete %></td>
            </tr>
            </tbody>
          <% end %>
      <% end %>
      </table>


</div>

app/views/items/new.html.erb
<%= render "layouts/header" %>
<div>
  <%= form_for(@item, url: items_path(@item)) do |f| %>
    <h2>商品</h2>
    <br>
    <%= f.label :category_id, "ジャンル" %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
    <%= f.label :category_id, "場所" %>
    <%= f.collection_select :place_id, Place.all, :id, :name %>
    <%= f.label :name, "名前" %>
    <%= f.text_field :name %>　　
    <%= f.select :count, (1..200) %>個
    <%= f.label :"賞味期限" %>
    <%= f.date_select(
            :expiration_date,
            use_month_numbers: true, # jan, febとかじゃなくて数字で月を表現
            start_year: (Time.now.year - 5), # 何年から表示させるか
            end_year: (Time.now.year + 20), # 何年まで表示させるか
            default: Date.new(1989, 1, 1), # 最初に表示されている年月日
            date_separator: '/') # 年月日を仕切る文字
    %>
    <%= f.submit "追加", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div>
  <nav class="navbar navbar-default">
    <nav>
      <%= link_to 'HOME', items_path %>
      <%= link_to "商品登録", new_item_path %>
      <%= link_to "ジャンル登録", new_category_path %>
      <%= link_to "場所登録", new_place_path %>
    </nav>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shiwake</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/places/new.html.erb
<%= render "layouts/header" %>
<%= form_for(@place, url: places_path(@place)) do |f| %>
  <h4>場所</h4>
  <br>
  <%= f.text_field :name %>
  <%= f.submit "追加", class: "btn btn-primary" %>
<% end %>
<br>
<table class="table  table-inverse">
  <thead>
  <tr>
    <% @places.each do |place| %>

      <th><%= place.name %></th>
      <th><%= link_to '消去', place_path(place), method: :delete %></th>

    <% end %>
  </tr>
  </thead>
</table>

app/views/places/show.html.erb
<%= render "layouts/header" %>
<table class="table table-bordered">
  <tbody>
  <th>カテゴリー</th>
  <% @categories.each do |category| %>

    <th><%= link_to category.name, category_path(category) %></th>
  <% end %>
  </tbody>
  <tbody>
  <th>場所</th>
  <% @places.each do |place| %>

    <th><%= link_to place.name, place_path(place) %></th>
  <% end %>

  </tbody>
</table>
<div>

  <h2>商品一覧（全<%= @items.count %>件）</h2>

  <table class="table  table-inverse">
    <thead>
    <tr>
      <th>名前</th>
      <th>ジャンル</th>
      <th>場所</th>
      <th>賞味期限</th>
      <th>個数</th>
    </tr>
    </thead>

    <tbody>

    <tr>
      <% @items.each do |item| %>
        <td><%= item.name %></td>

        <% category = Category.find(item.category_id) %>
        <td><%= category.name %></td>

        <% place = Place.find(item.place_id) %>
        <td><%= place.name %></td>
        <td><%= item.expiration_date %></td>


        <td>
          <%= form_for(item, url: item_path(item), method: :patch) do |f| %>
            <%= f.select :count, (1..200) %>
            <%= f.submit "変更する" %>
            </td>

            <td><%= link_to '消去', item_path(item), method: :delete %></td>
            </tr>
            </tbody>
          <% end %>
      <% end %>
      </table>


</div>